### ISSUE TITLE
under /pkg/golang/golang.go can support domestic go mod operation and set goproxy= https://goproxy.cn ,direct

### ISSUE THREAD

**Issue by fengpengyun** [OpenFunction/builder#14] opened 2021-09-17 02:34 UTC
func ExecWithGoproxyFallback(ctx *gcp.Context, cmd []string, opts ...gcp.ExecOption) *gcp.ExecResult {
	if SupportsGoProxyFallback(ctx) {
		goProxy := os.Getenv(env.GoProxy)
		if goProxy != "" {
			opts = append(opts, gcp.WithEnv(goProxy))
		}
		return ctx.Exec(cmd, opts...)
	}

	result, err := ctx.ExecWithErr(cmd, opts...)
	if err == nil {
		return result
	}
	ctx.Warnf("%q failed. Retrying with GOSUMDB=off GOPROXY=direct. Error: %v", strings.Join(cmd, " "), err)
        
	opts = append(opts, gcp.WithEnv("GOSUMDB=off", "GOPROXY=direct"))
	return ctx.Exec(cmd, opts...)
}

**Comment by tpiperatgod** [comment] 2021-09-17 02:49
By setting **FUNC_GOPROXY** you can use "https://goproxy.cn,direct"

**Comment by fengpengyun** [comment] 2021-09-17 03:17
1.under Function yaml setting：
 build:
    builder: openfunctiondev/go115-builder:v0.2.0
    env:
      FUNC_NAME: "LogsHandler"
      FUNC_GOPROXY: "https://goproxy.cn,direct"
2.but under build step create：
WARNING: "go mod tidy" failed. Retrying with GOSUMDB=off GOPROXY=direct. Error: go: github.com/OpenFunction/functions-framework-go@v0.0.0-20210628081257-4137e46a99a6: Get "https://proxy.golang.org/github.com/%!o(MISSING)pen%!f(MISSING)unction/functions-framework-go/@v/v0.0.0-20210628081257-4137e46a99a6.mod": dial tcp 142.251.42.241:443: i/o timeout [id:32633c29]

From the code, function supportsgoproxyfallback (CTX) returns false, but I use go115 image
so ，Is that why?
thanks。

**Comment by tpiperatgod** [comment] 2021-09-17 04:36
It's my mistake, you should use the FUNC_GOPROXY like the following:

```shell
--env FUNC_GOPROXY="GOPROXY=https://goproxy.cn,direct"
```

then the result will like:

```shell
[builder] --------------------------------------------------------------------------------
[builder] Running "go get github.com/OpenFunction/functions-framework-go@v0.0.0-20210628081257-4137e46a99a6 (GOPROXY=https://goproxy.cn,direct)"
[builder] go: downloading github.com/OpenFunction/functions-framework-go v0.0.0-20210628081257-4137e46a99a6
[builder] Done "go get github.com/OpenFunction/functions-framework-go@v0.0.0..." (7.201414527s)
[builder] === Go - Build (google.go.build@0.9.0) ===
[builder] --------------------------------------------------------------------------------
[builder] Running "go list -f {{if eq .Name \"main\"}}{{.Dir}}{{end}} ./... (GOPROXY=https://goproxy.cn,direct)"
[builder] /workspace
[builder] Done "go list -f {{if eq .Name \"main\"}}{{.Dir}}{{end}} ./... (GOPR..." (2.025105584s)
[builder] --------------------------------------------------------------------------------
[builder] Running "go build -o /layers/google.go.build/bin/main ./. (GOCACHE=/layers/google.go.build/gocache CGO_ENABLED=0 GOPROXY=https://goproxy.cn,direct)"
```

**Comment by benjaminhuo** [comment] 2021-09-17 05:39
Now goproxy can be set this way, we'll make it more reasonable

```yaml
env:
    FUNC_NAME: "LogsHandler"
    FUNC_GOPROXY="GOPROXY=https://goproxy.cn,direct"
```

**Comment by tpiperatgod** [comment] 2021-09-17 06:32
@fengpengyun Hi, I have submitted a PR to improve this, and it will be merged into the latest builder image in the next release. In the meantime, you can build the builder image yourself from the main branch and use the new FUNC_GOPROXY environment parameters through this image. 

thx.

**Comment by fengpengyun** [comment] 2021-09-17 06:37
1.under Function yaml setting：
`build:
    builder: openfunctiondev/go116-builder:v0.2.0
    env:
      FUNC_NAME: "LogsHandler"
      FUNC_GOPROXY: "GOPROXY=https://goproxy.cn,direct"
`
2.but under build step create,：
WARNING: "go mod tidy" failed. Retrying with GOSUMDB=off GOPROXY=direct. Error: go: github.com/OpenFunction/functions-framework-go@v0.0.0-20210628081257-4137e46a99a6: Get "https://proxy.golang.org/github.com/%!o(MISSING)pen%!f(MISSING)unction/functions-framework-go/@v/v0.0.0-20210628081257-4137e46a99a6.mod": dial tcp 172.217.24.17:443: i/o timeout [id:32633c29]

We can see that WARNING: "go mod tidy" failed. Retrying with GOSUMDB=off GOPROXY=direct. 
The warning is ctx.Warnf("% q failed. Retrying with gosumdb = off goproxy = direct. Error:% v", strings. Join (cmd, ""), err) in pkg/golang/golang.go, indicating that supportsgoproxyfallback (CTX) is false, that is, the current go version is less than 1.15, which is inconsistent with the actual situation.

**Comment by tpiperatgod** [comment] 2021-09-17 07:22
I built the new builders, and you can use **openfunctiondev/go115-builder:v0.2.1** (for go 1.15) and **openfunctiondev/go116-builder:v0.2.1** (for go 1.16) to build the image

These two images will allow you to use the following environment variables
```shell
FUNC_GOPROXY="https://goproxy.cn,direct"
```
However, due to some problems in the OpenFunction build controller, the above FUNC_GOPROXY will be resolved to "https://goproxy.cn", which we will fix later

thx.

**Comment by benjaminhuo** [comment] 2021-09-17 07:55
> I built the new builders, and you can use **openfunctiondev/go115-builder:v0.2.1** (for go 1.15) and **openfunctiondev/go116-builder:v0.2.1** (for go 1.16) to build the image
> 
> These two images will allow you to use the following environment variables
> 
> ```shell
> FUNC_GOPROXY="https://goproxy.cn,direct"
> ```
> 
> However, due to some problems in the OpenFunction build controller, the above FUNC_GOPROXY will be resolved to "https://goproxy.cn", which we will fix later
> 
> thx.

@fengpengyun does this solve your problem? You used OpenFunction for what kind of scenario?

**Comment by fengpengyun** [comment] 2021-09-17 08:20
It hasn't been solved yet. I think before execwithgoproxyfallback is executed, the attributes required by supportsgoproxyfallback (ctx) are not added to its parameter ctx, resulting in no reading of the set goproxy。
  
  at KS's sharing meeting, I saw openfunction and was more interested in it. It's like learning. I haven't used it yet, but there are scenes to try in the future.
@benjaminhuo

**Comment by tpiperatgod** [comment] 2021-09-17 08:28
Can you provide detailed steps? and the runtime environment (e.g. go version, os, etc.)

Or if possible, the **TaskRun** logs in the Tekton dashboard?

**Comment by benjaminhuo** [comment] 2021-09-17 08:29
> It hasn't been solved yet. I think before execwithgoproxyfallback is executed, the attributes required by supportsgoproxyfallback (ctx) are not added to its parameter ctx, resulting in no reading of the set goproxy。
> 
> at KS's sharing meeting, I saw openfunction and was more interested in it. It's like learning. I haven't used it yet, but there are scenes to try in the future.
> @benjaminhuo

Doesn't work if you modify like this?

```yaml
apiVersion: core.openfunction.io/v1alpha1
kind: Function
metadata:
  name: logs-sync-handler
spec:
  version: "v1.0.0"
  image: openfunctiondev/logs-sync-handler:v1
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/go115-builder:**v0.2.1**
    env:
      FUNC_NAME: "LogsHandler"
      FUNC_GOPROXY: *"https://goproxy.cn"*
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Knative/logs-handler-function/"
  serving:
    runtime: "Knative"
```

**Comment by benjaminhuo** [comment] 2021-09-17 08:31
> Can you provide detailed steps? and the runtime environment (e.g. go version, os, etc.)
> 
> Or if possible, the **TaskRun** logs in the Tekton dashboard?

A full function yaml will be good

**Comment by fengpengyun** [comment] 2021-09-17 08:54
`
apiVersion: core.openfunction.io/v1alpha1
kind: Function
metadata:
  name: logs-handler
spec:
  version: "v1.0.0"
  image: openfunctiondev/logs-async-handler:v1
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/go115-builder:v0.2.1
    env:
      FUNC_NAME: "LogsHandler"
      FUNC_GOPROXY: "https://goproxy.cn,direct"
    srcRepo:
      url: "https://gitee.com/fengpengyun/openfunction-samples.git"
      sourceSubPath: "functions/OpenFuncAsync/logs-handler-function/"
  serving:
    runtime: "OpenFuncAsync"
    openFuncAsync:
      dapr:
        inputs:
          - name: kafka-receiver
            type: bindings
        outputs:
          - name: notification-manager
            type: bindings
            params:
              operation: "post"
              type: "bindings"
        annotations:
          dapr.io/log-level: "debug"
        components:
          - name: kafka-receiver
            type: bindings.kafka
            version: v1
            metadata:
              - name: brokers
                value: "kafka-logs-receiver-kafka-brokers:9092"
              - name: authRequired
                value: "false"
              - name: publishTopic
                value: "logs"
              - name: topics
                value: "logs"
              - name: consumerGroup
                value: "logs-handler"
          - name: notification-manager
            type: bindings.http
            version: v1
            metadata:
              - name: url
                value: http://notification-manager-svc.kubesphere-monitoring-system.svc.cluster.local:19093/api/v2/alerts
      keda:
        scaledObject:
          pollingInterval: 15
          minReplicaCount: 0
          maxReplicaCount: 10
          cooldownPeriod: 30
          triggers:
            - type: kafka
              metadata:
                topic: logs
                bootstrapServers: kafka-logs-receiver-kafka-brokers.default.svc.cluster.local:9092
                consumerGroup: logs-handler
                lagThreshold: "10"
`
this is a full function yaml
@benjaminhuo @tpiperatgod

**Comment by fengpengyun** [comment] 2021-09-17 08:58
apiVersion: core.openfunction.io/v1alpha1
kind: Function
metadata:
  name: logs-handler
spec:
  version: "v1.0.0"
  image: openfunctiondev/logs-async-handler:v1
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/go115-builder:v0.2.1
    env:
      FUNC_NAME: "LogsHandler"
      FUNC_GOPROXY: "https://goproxy.cn,direct"
    srcRepo:
      url: "https://gitee.com/fengpengyun/openfunction-samples.git"
      sourceSubPath: "functions/OpenFuncAsync/logs-handler-function/"
  serving:
    runtime: "OpenFuncAsync"
    openFuncAsync:
      dapr:
        inputs:
          - name: kafka-receiver
            type: bindings
        outputs:
          - name: notification-manager
            type: bindings
            params:
              operation: "post"
              type: "bindings"
        annotations:
          dapr.io/log-level: "debug"
        components:
          - name: kafka-receiver
            type: bindings.kafka
            version: v1
            metadata:
              - name: brokers
                value: "kafka-logs-receiver-kafka-brokers:9092"
              - name: authRequired
                value: "false"
              - name: publishTopic
                value: "logs"
              - name: topics
                value: "logs"
              - name: consumerGroup
                value: "logs-handler"
          - name: notification-manager
            type: bindings.http
            version: v1
            metadata:
              - name: url
                value: http://notification-manager-svc.kubesphere-monitoring-system.svc.cluster.local:19093/api/v2/alerts
      keda:
        scaledObject:
          pollingInterval: 15
          minReplicaCount: 0
          maxReplicaCount: 10
          cooldownPeriod: 30
          triggers:
            - type: kafka
              metadata:
                topic: logs
                bootstrapServers: kafka-logs-receiver-kafka-brokers.default.svc.cluster.local:9092
                consumerGroup: logs-handler
                lagThreshold: "10"
This is a full function yaml.
@tpiperatgod @benjaminhuo

**Comment by fengpengyun** [comment] 2021-09-17 09:05
``
apiVersion: core.openfunction.io/v1alpha1
kind: Function
metadata:
  name: logs-handler
spec:
  version: "v1.0.0"
  image: openfunctiondev/logs-async-handler:v1
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/go115-builder:v0.2.1
    env:
      FUNC_NAME: "LogsHandler"
      FUNC_GOPROXY: "https://goproxy.cn,direct"
    srcRepo:
      url: "https://gitee.com/fengpengyun/openfunction-samples.git"
      sourceSubPath: "functions/OpenFuncAsync/logs-handler-function/"
  serving:
    runtime: "OpenFuncAsync"
    openFuncAsync:
      dapr:
        inputs:
          - name: kafka-receiver
            type: bindings
        outputs:
          - name: notification-manager
            type: bindings
            params:
              operation: "post"
              type: "bindings"
        annotations:
          dapr.io/log-level: "debug"
        components:
          - name: kafka-receiver
            type: bindings.kafka
            version: v1
            metadata:
              - name: brokers
                value: "kafka-logs-receiver-kafka-brokers:9092"
              - name: authRequired
                value: "false"
              - name: publishTopic
                value: "logs"
              - name: topics
                value: "logs"
              - name: consumerGroup
                value: "logs-handler"
          - name: notification-manager
            type: bindings.http
            version: v1
            metadata:
              - name: url
                value: http://notification-manager-svc.kubesphere-monitoring-system.svc.cluster.local:19093/api/v2/alerts
      keda:
        scaledObject:
          pollingInterval: 15
          minReplicaCount: 0
          maxReplicaCount: 10
          cooldownPeriod: 30
          triggers:
            - type: kafka
              metadata:
                topic: logs
                bootstrapServers: kafka-logs-receiver-kafka-brokers.default.svc.cluster.local:9092
                consumerGroup: logs-handler
                lagThreshold: "10"
``This is a full function yaml
@tpiperatgod  @benjaminhuo

**Comment by fengpengyun** [comment] 2021-09-17 09:08
```yaml
apiVersion: core.openfunction.io/v1alpha1
kind: Function
metadata:
  name: logs-handler
spec:
  version: "v1.0.0"
  image: openfunctiondev/logs-async-handler:v1
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/go115-builder:v0.2.1
    env:
      FUNC_NAME: "LogsHandler"
      FUNC_GOPROXY: "https://goproxy.cn,direct"
    srcRepo:
      url: "https://gitee.com/fengpengyun/openfunction-samples.git"
      sourceSubPath: "functions/OpenFuncAsync/logs-handler-function/"
  serving:
    runtime: "OpenFuncAsync"
    openFuncAsync:
      dapr:
        inputs:
          - name: kafka-receiver
            type: bindings
        outputs:
          - name: notification-manager
            type: bindings
            params:
              operation: "post"
              type: "bindings"
        annotations:
          dapr.io/log-level: "debug"
        components:
          - name: kafka-receiver
            type: bindings.kafka
            version: v1
            metadata:
              - name: brokers
                value: "kafka-logs-receiver-kafka-brokers:9092"
              - name: authRequired
                value: "false"
              - name: publishTopic
                value: "logs"
              - name: topics
                value: "logs"
              - name: consumerGroup
                value: "logs-handler"
          - name: notification-manager
            type: bindings.http
            version: v1
            metadata:
              - name: url
                value: http://notification-manager-svc.kubesphere-monitoring-system.svc.cluster.local:19093/api/v2/alerts
      keda:
        scaledObject:
          pollingInterval: 15
          minReplicaCount: 0
          maxReplicaCount: 10
          cooldownPeriod: 30
          triggers:
            - type: kafka
              metadata:
                topic: logs
                bootstrapServers: kafka-logs-receiver-kafka-brokers.default.svc.cluster.local:9092
                consumerGroup: logs-handler
                lagThreshold: "10"
```
This is a full function yaml.
@tpiperatgod @benjaminhuo

**Comment by tpiperatgod** [comment] 2021-09-17 10:13
I'll verify what you're describing in an environment with limited access to google, thanks for reporting

**Comment by tpiperatgod** [comment] 2021-09-17 16:02
The problem is that when functions-framework buildpacks are executed, there is no go.mod in the environment, which causes the following function, **SupportsGoProxyFallback(ctx)** to return false

```go
func ExecWithGoproxyFallback(ctx *gcp.Context, cmd []string, opts . . gcp.ExecOption) *gcp.ExecResult {
	if SupportsGoProxyFallback(ctx) || ctx.BuildpackID() == OpenFunctionFunctionsFrameworkLayer {
		goProxy := os.Getenv(env.GoProxy)
		if goProxy ! = "" {
			opts = append(opts, gcp.WithEnv(fmt.Sprintf("GOPROXY=%s", goProxy)))
		}
		return ctx.Exec(cmd, opts...)
	}

	result, err := ctx.ExecWithErr(cmd, opts...)
	if err == nil {
		return result
	}
	ctx.Warnf("%q failed. Retrying with GOSUMDB=off GOPROXY=direct. Error: %v", strings.Join(cmd, " "), err)

	opts = append(opts, gcp.WithEnv("GOSUMDB=off", "GOPROXY=direct"))
	return ctx.Exec(cmd, opts...)
}
```
 
I made a workaround image **openfunctiondev/go115-builder:v0.2.2** that works correctly with the FUNC_GOPROXY variable.

And I will fix this bug later and upload new builder images.

**Closed** 2021-09-18 02:06 UTC
Labels: bug

**Comment by fengpengyun** [comment] 2021-09-18 02:11
## under serving function has register err
2021/09/18 01:48:43 Failed to register: Function failed to register: unrecognized function

So I checked functions code of  of_functions_framework / template.go.
```go
func register(fn interface{}) error {
	ctx := context.Background()
	if fnHTTP, ok := fn.(func(http.ResponseWriter, *http.Request)); ok {
		if err := functionframeworks.RegisterHTTPFunction(ctx, fnHTTP); err != nil {
			return fmt.Errorf("Function failed to register: %v\n", err)
		}
	} else if fnCloudEvent, ok := fn.(func(context.Context, cloudevents.Event) error); ok {
		if err := functionframeworks.RegisterCloudEventFunction(ctx, fnCloudEvent); err != nil {
			return fmt.Errorf("Function failed to register: %v\n", err)
		}
	} else if fnOpenFunction, ok := fn.(func(*ofctx.OpenFunctionContext, []byte) int); ok {
		if err := functionframeworks.RegisterOpenFunction(ctx, fnOpenFunction); err != nil {
			return fmt.Errorf("Function failed to register: %v\n", err)
		}
	} else {
		err := errors.New("unrecognized function")
		return fmt.Errorf("Function failed to register: %v\n", err)
	}
	return nil
}
```
It will output err after else, that is, it does not recognize 
```go
fn.(func(*ofctx.OpenFunctionContext, []byte) int)
```
@tpiperatgod

**Comment by tpiperatgod** [comment] 2021-09-18 02:15
> ## under serving function has register err
> 2021/09/18 01:48:43 Failed to register: Function failed to register: unrecognized function
> 
> So I checked functions code of of_functions_framework / template.go.
> 
> ```go
> func register(fn interface{}) error {
> 	ctx := context.Background()
> 	if fnHTTP, ok := fn.(func(http.ResponseWriter, *http.Request)); ok {
> 		if err := functionframeworks.RegisterHTTPFunction(ctx, fnHTTP); err != nil {
> 			return fmt.Errorf("Function failed to register: %v\n", err)
> 		}
> 	} else if fnCloudEvent, ok := fn.(func(context.Context, cloudevents.Event) error); ok {
> 		if err := functionframeworks.RegisterCloudEventFunction(ctx, fnCloudEvent); err != nil {
> 			return fmt.Errorf("Function failed to register: %v\n", err)
> 		}
> 	} else if fnOpenFunction, ok := fn.(func(*ofctx.OpenFunctionContext, []byte) int); ok {
> 		if err := functionframeworks.RegisterOpenFunction(ctx, fnOpenFunction); err != nil {
> 			return fmt.Errorf("Function failed to register: %v\n", err)
> 		}
> 	} else {
> 		err := errors.New("unrecognized function")
> 		return fmt.Errorf("Function failed to register: %v\n", err)
> 	}
> 	return nil
> }
> ```
> 
> It will output err after else, that is, it does not recognize
> 
> ```go
> fn.(func(*ofctx.OpenFunctionContext, []byte) int)
> ```
> 
> @tpiperatgod

Is this a new issue? If it's, you can create a new issue in the [functions-framework-go](https://github.com/OpenFunction/functions-framework-go) repo, which will help track the issue

**Comment by benjaminhuo** [comment] 2021-09-18 02:16
The sample code is old and the function framework go has been updated, right? @tpiperatgod

**Comment by fengpengyun** [comment] 2021-09-18 02:23
Ok, I has create a new issue in the functions-framework-go repo。 @tpiperatgod

**Comment by tpiperatgod** [comment] 2021-09-18 02:34
> The sample code is old and the function framework go has been updated, right? @tpiperatgod

Yes, I mistakenly committed the new functions-framework-go to the workaround image

> Ok, I has create a new issue in the functions-framework-go repo。 @tpiperatgod

Thx.
